# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\coding\python\chat_advanced\recode\Websocket Test\createacc.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(100, 203, 255, 255), stop:1 rgba(184, 255, 118, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(530, 100, 201, 61))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 160, 301, 61))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.create = QtWidgets.QPushButton(self.bgwidget)
        self.create.setGeometry(QtCore.QRect(480, 570, 301, 41))
        self.create.setStyleSheet("border-radius:16px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.create.setObjectName("create")
        self.confirmpassword = QtWidgets.QLineEdit(self.bgwidget)
        self.confirmpassword.setGeometry(QtCore.QRect(480, 477, 301, 41))
        self.confirmpassword.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.confirmpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpassword.setObjectName("confirmpassword")
        self.password = QtWidgets.QLineEdit(self.bgwidget)
        self.password.setGeometry(QtCore.QRect(480, 390, 301, 41))
        self.password.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.username = QtWidgets.QLineEdit(self.bgwidget)
        self.username.setGeometry(QtCore.QRect(480, 300, 301, 41))
        self.username.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.username.setObjectName("username")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 280, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 370, 51, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 460, 90, 16))
        self.label_5.setObjectName("label_5")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(480, 530, 300, 13))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: red;\n"
"")
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sign up"))
        self.label_2.setText(_translate("Dialog", "Register a brand new account"))
        self.create.setText(_translate("Dialog", "Sign Up"))
        self.label_3.setText(_translate("Dialog", "Username"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.label_5.setText(_translate("Dialog", "Confirm Password"))
